version: '3.8'

services:
  # Prometheus for metrics collection
  prometheus:
    image: prom/prometheus:latest
    container_name: onlyvips-prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    networks:
      - onlyvips-monitoring

  # Grafana for visualization
  grafana:
    image: grafana/grafana:latest
    container_name: onlyvips-grafana
    restart: always
    ports:
      - "3003:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=onlyvips123
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/dashboards:/etc/grafana/dashboards
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
    networks:
      - onlyvips-monitoring

  # Loki for log aggregation
  loki:
    image: grafana/loki:latest
    container_name: onlyvips-loki
    restart: always
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yml:/etc/loki/loki-config.yml
      - loki-data:/loki
    command: -config.file=/etc/loki/loki-config.yml
    networks:
      - onlyvips-monitoring

  # Promtail for log collection
  promtail:
    image: grafana/promtail:latest
    container_name: onlyvips-promtail
    restart: always
    volumes:
      - ./promtail-config.yml:/etc/promtail/promtail-config.yml
      - /var/log:/var/log
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    command: -config.file=/etc/promtail/promtail-config.yml
    depends_on:
      - loki
    networks:
      - onlyvips-monitoring

  # AlertManager for alert handling
  alertmanager:
    image: prom/alertmanager:latest
    container_name: onlyvips-alertmanager
    restart: always
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - alertmanager-data:/alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
    networks:
      - onlyvips-monitoring

  # Node Exporter for host metrics
  node-exporter:
    image: prom/node-exporter:latest
    container_name: onlyvips-node-exporter
    restart: always
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - onlyvips-monitoring

  # Redis for caching (production)
  redis:
    image: redis:7-alpine
    container_name: onlyvips-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes --requirepass onlyvips_redis_pass
    networks:
      - onlyvips-monitoring

volumes:
  prometheus-data:
  grafana-data:
  loki-data:
  alertmanager-data:
  redis-data:

networks:
  onlyvips-monitoring:
    driver: bridge 