# OnlyVips Platform Staging Secret Değerleri
# Bu dosya gizli bilgileri içerir ve gitignore'a eklenmelidir.
# UYARI: BU DOSYAYI GIT REPOSUNA EKLEMEYİN!

# Global değerler
global:
  # Telegram yapılandırması
  telegram:
    apiId: "your-telegram-api-id" # DEĞİŞTİRİN
    apiHash: "your-telegram-api-hash" # DEĞİŞTİRİN
    botToken: "your-telegram-bot-token" # DEĞİŞTİRİN
    sessionString: "your-session-string-if-any" # DEĞİŞTİRİN
  
  # Veritabanı kullanıcı bilgileri
  postgresql:
    auth:
      password: "postgresql-password" # DEĞİŞTİRİN
  
  # Redis kimlik bilgileri
  redis:
    auth:
      password: "redis-password" # DEĞİŞTİRİN
  
  # MongoDB kimlik bilgileri  
  mongodb:
    auth:
      rootPassword: "mongodb-root-password" # DEĞİŞTİRİN
      password: "mongodb-user-password" # DEĞİŞTİRİN

# Backend API secret değerleri
backend:
  env:
    SECRET_KEY: "backend-secret-key-change-this" # DEĞİŞTİRİN
    JWT_SECRET: "jwt-secret-key-change-this" # DEĞİŞTİRİN
    OPENAI_API_KEY: "your-openai-api-key-if-any" # DEĞİŞTİRİN 