{{- if and .Values.global.canary .Values.global.canary.enabled }}
# Canary deployment yapılandırması
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-canary
  labels:
    app: {{ .Release.Name }}-canary
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  hosts:
    - api.onlyvips.xyz
    - app.onlyvips.xyz
    - panel.onlyvips.xyz
  gateways:
    - {{ .Release.Name }}-gateway
  http:
    # Backend API için canary configuration
    - match:
        - uri:
            prefix: /api
          host: api.onlyvips.xyz
      route:
        - destination:
            host: {{ .Values.backend.name }}
            port:
              number: {{ .Values.backend.service.port }}
          weight: {{ sub 100 (int .Values.global.canary.weight) }}
        - destination:
            host: {{ .Values.backend.name }}-canary
            port:
              number: {{ .Values.backend.service.port }}
          weight: {{ .Values.global.canary.weight }}
      
    # MiniApp için canary configuration
    - match:
        - uri:
            prefix: /
          host: app.onlyvips.xyz
      route:
        - destination:
            host: {{ .Values.miniapp.name }}
            port:
              number: {{ .Values.miniapp.service.port }}
          weight: {{ sub 100 (int .Values.global.canary.weight) }}
        - destination:
            host: {{ .Values.miniapp.name }}-canary
            port:
              number: {{ .Values.miniapp.service.port }}
          weight: {{ .Values.global.canary.weight }}
      
    # Showcu Panel için canary configuration
    - match:
        - uri:
            prefix: /
          host: panel.onlyvips.xyz
      route:
        - destination:
            host: {{ .Values.showcuPanel.name }}
            port:
              number: {{ .Values.showcuPanel.service.port }}
          weight: {{ sub 100 (int .Values.global.canary.weight) }}
        - destination:
            host: {{ .Values.showcuPanel.name }}-canary
            port:
              number: {{ .Values.showcuPanel.service.port }}
          weight: {{ .Values.global.canary.weight }}
{{- end }}

{{- if and .Values.global.canary .Values.global.canary.enabled }}
---
# Backend Canary Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.name }}-canary
  labels:
    app: {{ .Values.backend.name }}-canary
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    version: canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.backend.name }}-canary
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Values.backend.name }}-canary
        release: {{ .Release.Name }}
        version: canary
    spec:
      containers:
        - name: {{ .Values.backend.name }}-canary
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.backend.service.port }}
              protocol: TCP
          env:
            - name: NODE_ENV
              value: {{ .Values.global.environment }}
            - name: PORT
              value: "{{ .Values.backend.service.port }}"
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: mongodb-uri
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: secret-key
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: jwt-secret
            - name: CANARY
              value: "true"
          livenessProbe:
            {{- toYaml .Values.backend.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.backend.readinessProbe | nindent 12 }}
---
# Backend Canary Service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.name }}-canary
  labels:
    app: {{ .Values.backend.name }}-canary
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    version: canary
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.backend.name }}-canary
    release: {{ .Release.Name }}
---
# MiniApp Canary Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.miniapp.name }}-canary
  labels:
    app: {{ .Values.miniapp.name }}-canary
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    version: canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.miniapp.name }}-canary
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Values.miniapp.name }}-canary
        release: {{ .Release.Name }}
        version: canary
    spec:
      containers:
        - name: {{ .Values.miniapp.name }}-canary
          image: "{{ .Values.miniapp.image.repository }}:{{ .Values.miniapp.image.tag }}"
          imagePullPolicy: {{ .Values.miniapp.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.miniapp.service.port }}
              protocol: TCP
          env:
            - name: CANARY
              value: "true"
          livenessProbe:
            {{- toYaml .Values.miniapp.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.miniapp.readinessProbe | nindent 12 }}
---
# MiniApp Canary Service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.miniapp.name }}-canary
  labels:
    app: {{ .Values.miniapp.name }}-canary
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    version: canary
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.miniapp.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.miniapp.name }}-canary
    release: {{ .Release.Name }}
---
# Showcu Panel Canary Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.showcuPanel.name }}-canary
  labels:
    app: {{ .Values.showcuPanel.name }}-canary
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    version: canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.showcuPanel.name }}-canary
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Values.showcuPanel.name }}-canary
        release: {{ .Release.Name }}
        version: canary
    spec:
      containers:
        - name: {{ .Values.showcuPanel.name }}-canary
          image: "{{ .Values.showcuPanel.image.repository }}:{{ .Values.showcuPanel.image.tag }}"
          imagePullPolicy: {{ .Values.showcuPanel.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.showcuPanel.service.port }}
              protocol: TCP
          env:
            - name: CANARY
              value: "true"
          livenessProbe:
            {{- toYaml .Values.showcuPanel.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.showcuPanel.readinessProbe | nindent 12 }}
---
# Showcu Panel Canary Service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.showcuPanel.name }}-canary
  labels:
    app: {{ .Values.showcuPanel.name }}-canary
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    version: canary
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.showcuPanel.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.showcuPanel.name }}-canary
    release: {{ .Release.Name }}
{{- end }} 