apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.flirtBot.name }}
  labels:
    app: {{ .Values.flirtBot.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.flirtBot.service.type }}
  ports:
    - port: {{ .Values.flirtBot.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.flirtBot.name }}
    release: {{ .Release.Name }} 