apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.miniapp.name }}
  labels:
    app: {{ .Values.miniapp.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.miniapp.service.type }}
  ports:
    - port: {{ .Values.miniapp.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.miniapp.name }}
    release: {{ .Release.Name }} 