{{- if .Values.persistence.enabled }}
# Backend uploads PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.backend.name }}-uploads-pvc
  labels:
    app: {{ .Values.backend.name }}
    release: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.uploads.size }}
---
# Backend logs PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.backend.name }}-logs-pvc
  labels:
    app: {{ .Values.backend.name }}
    release: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.logs.size }}
---
# Flirt Bot sessions PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.flirtBot.name }}-sessions-pvc
  labels:
    app: {{ .Values.flirtBot.name }}
    release: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.sessions.size }}
---
# Flirt Bot logs PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.flirtBot.name }}-logs-pvc
  labels:
    app: {{ .Values.flirtBot.name }}
    release: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.logs.size }}
{{- end }} 