apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  # Backend secret değerleri
  secret-key: {{ .Values.backend.env.SECRET_KEY | b64enc | quote }}
  jwt-secret: {{ .Values.backend.env.JWT_SECRET | b64enc | quote }}
  mongodb-uri: {{ printf "mongodb://%s:%s@%s/%s?authSource=admin" .Values.global.mongodb.auth.username .Values.global.mongodb.auth.password (printf "%s-mongodb" .Release.Name) .Values.global.mongodb.auth.database | b64enc | quote }}
  telegram-api-id: {{ .Values.global.telegram.apiId | b64enc | quote }}
  telegram-api-hash: {{ .Values.global.telegram.apiHash | b64enc | quote }}
  telegram-bot-token: {{ .Values.global.telegram.botToken | b64enc | quote }}
  openai-api-key: {{ .Values.backend.env.OPENAI_API_KEY | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: flirtbot-secret
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  # Flirt Bot secret değerleri
  telegram-api-id: {{ .Values.global.telegram.apiId | b64enc | quote }}
  telegram-api-hash: {{ .Values.global.telegram.apiHash | b64enc | quote }}
  telegram-bot-token: {{ .Values.global.telegram.botToken | b64enc | quote }}
  session-string: {{ .Values.global.telegram.sessionString | default "" | b64enc | quote }}
  openai-api-key: {{ .Values.backend.env.OPENAI_API_KEY | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  # PostgreSQL secret değerleri
  postgres-password: {{ .Values.global.postgresql.auth.password | b64enc | quote }}
  password: {{ .Values.global.postgresql.auth.password | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  # Redis secret değerleri
  redis-password: {{ .Values.global.redis.auth.password | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  # MongoDB secret değerleri
  mongodb-root-password: {{ .Values.global.mongodb.auth.rootPassword | b64enc | quote }}
  mongodb-password: {{ .Values.global.mongodb.auth.password | b64enc | quote }} 